server:
  port: 8011

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: player-service

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]  # Expose all actuator endpoints
  endpoint:
    metrics:
      web:
        exposure:
          include: '*'  # Expose all metrics


prometheus:
  job-name: 'spring-actuator'
  scrape-interval: 15s  # Adjust as needed


logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG