global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    static_configs:
      - targets: ['10.154.112.59:player-service:8011']  # Replace with your Spring Boot application's address
